kruize/kruize

src/main/java/com/kruize/collection/CollectMetrics.java

@dinogun Should fix the memory usage dipping to zero. Tested on ICP.

Fix current memory usage

---

README.md
manifests/kruize.yaml_template
src/main/java/com/kruize/environment/kubernetes/KubernetesEnvImpl.java

Change app label to match specifications

---

deploy.sh

Included username, password and namespace as arguments to cloudctl and removed nodeselector
#13 
Signed-off-by: Chandrakala M Subramanyam <chandra-ms@in.ibm.com>

Included user credentials as arguments to cloudctl 

---

src/main/java/com/kruize/analysis/AnalysisImpl.java
src/main/java/com/kruize/analysis/docker/DockerAnalysisImpl.java
src/main/java/com/kruize/analysis/kubernetes/KubernetesAnalysisImpl.java
src/main/java/com/kruize/collection/CollectMetrics.java
src/main/java/com/kruize/query/docker/DockerPrometheusQuery.java

Fix docker recommendations

---

Dockerfile

Add jdk.crypto.ec module to the jlinked jre to fix the ssl handshake

---

build.sh
deploy.sh

Add monitor loop to check deploy status.

---

src/main/java/com/kruize/analysis/AnalysisImpl.java
src/main/java/com/kruize/collection/CollectMetrics.java
src/main/java/com/kruize/environment/EnvTypeImpl.java
src/main/java/com/kruize/environment/SupportedTypes.java
src/main/java/com/kruize/environment/docker/DockerEnvImpl.java
src/main/java/com/kruize/environment/kubernetes/KubernetesEnvImpl.java
src/main/java/com/kruize/exceptions/ApplicationIdleStateException.java
src/main/java/com/kruize/exceptions/MonitoringAgentNotSupportedException.java
src/main/java/com/kruize/exceptions/env/ClusterTypeNotSupportedException.java
src/main/java/com/kruize/exceptions/env/K8sTypeNotSupportedException.java
src/main/java/com/kruize/initialize/Initialize.java
src/main/java/com/kruize/query/PrometheusQuery.java
src/main/java/com/kruize/query/kubernetes/KubernetesPrometheusQuery.java
src/main/java/com/kruize/util/HttpUtil.java
src/main/java/com/kruize/util/MathUtil.java

Add minikube support

---

src/main/java/com/kruize/environment/kubernetes/KubernetesEnvImpl.java

Check if endpoint is blank

---

src/main/java/com/kruize/environment/kubernetes/KubernetesEnvImpl.java
src/main/java/com/kruize/query/PrometheusQuery.java

Fixes #42 
Added default labels for when the list of labels was not able to be accessed, which resulted in an NPE in ICP.

Fix NPE for ICP when checking labels

---

deploy.sh
manifests/docker/kruize-docker.yaml

Add more default containers to be monitored in the docker usecase.
Signed-off-by: Dinakar Guniguntala <dinakar.g@in.ibm.com>

deploy.sh updates to gracefully handle prometheus installation and bringup issues.

---

src/main/java/com/kruize/environment/kubernetes/KubernetesEnvImpl.java

Fix IndexOutOfBoundsException when podName didn't contain hash

---

deploy.sh
manifests/kruize.yaml_template

Add automated (non-interactive) mode.

---

deploy.sh
scripts/docker-helpers.sh
scripts/icp-helpers.sh
scripts/minikube-helpers.sh
scripts/openshift-helpers.sh

Split deploy.sh to helper scripts for each deployment target as it has become too big to be contained in one script.

Add a timeout option for the docker usecase.

---

docs/README.md
manifests/kruize.yaml_template
pom.xml
src/main/java/com/kruize/analysis/Analysis.java
src/main/java/com/kruize/analysis/AnalysisImpl.java
src/main/java/com/kruize/collection/CollectMetrics.java
src/main/java/com/kruize/environment/Defaults.java
src/main/java/com/kruize/environment/docker/DockerDefaults.java
src/main/java/com/kruize/environment/docker/DockerEnvImpl.java
src/main/java/com/kruize/environment/kubernetes/KubernetesDefaults.java
src/main/java/com/kruize/environment/kubernetes/KubernetesEnvImpl.java
src/main/java/com/kruize/initialize/Initialize.java
src/main/java/com/kruize/main/Kruize.java
src/main/java/com/kruize/metrics/AbstractMetrics.java
src/main/java/com/kruize/recommendations/application/AbstractApplicationRecommendations.java
src/main/java/com/kruize/util/HttpUtil.java
src/main/java/com/kruize/util/MathUtil.java
src/main/resources/log4j2.properties

Closes #17 
1. Added log4j implementation of slf4j.
2. Added a log4j2.properties file for logging configuration.
3. Added a new env LOGGING_LEVEL that can be set in the YAML file.

Improve logging

---

.travis.yml

Fixes #48 
Signed-off-by: Chandrakala M Subramanyam <chandra-ms@in.ibm.com>

Included a travis test to validate kruize deployment

---

scripts/icp-helpers.sh
scripts/minikube-helpers.sh
scripts/openshift-helpers.sh

docker image name can have a "/", modify sed command accordingly.
Fail all deploy functions on error.

deploy.sh should handle errors gracefully

---

scripts/icp-helpers.sh

Fixes #87
Signed-off-by: Chandrakala M Subramanyam <chandra-ms@in.ibm.com>

Removed error check if service account exists

---

src/main/java/com/kruize/collection/CollectMetrics.java
src/main/java/com/kruize/metrics/AbstractMetrics.java
src/main/java/com/kruize/metrics/ContainerMetrics.java
src/main/java/com/kruize/metrics/Metrics.java
src/main/java/com/kruize/metrics/PodMetrics.java
src/main/java/com/kruize/recommendations/application/AbstractApplicationRecommendations.java

Signed-off-by: Ravali Yatham <yatraval@in.ibm.com>
Closes #59

Added function to get Pod status

---

src/main/java/com/kruize/environment/DeploymentInfo.java
src/main/java/com/kruize/environment/docker/DockerDefaults.java
src/main/java/com/kruize/initialize/Initialize.java
src/main/java/com/kruize/util/HttpUtil.java

Also move `logDeploymentInfo` method to `DeploymentInfo.java`

Move initialization validation logic to DeploymentInfo setters

---

scripts/build_sanity_test.sh

Print logs when build fails in travis

---

scripts/icp-helpers.sh

Add icp_terminate

---

README.md
scripts/docker-helpers.sh
scripts/icp-helpers.sh
scripts/minikube-helpers.sh
scripts/openshift-helpers.sh

Make deploy changes to support macOS

---

scripts/minikube-helpers.sh

Add minikube_terminate

---

src/main/java/com/kruize/analysis/AnalysisImpl.java
src/main/java/com/kruize/collection/CollectMetrics.java
src/main/java/com/kruize/environment/docker/DockerEnvImpl.java
src/main/java/com/kruize/environment/kubernetes/KubernetesEnvImpl.java
src/main/java/com/kruize/initialize/Initialize.java
src/main/java/com/kruize/main/Kruize.java
src/main/java/com/kruize/metrics/MetricsImpl.java
src/main/java/com/kruize/recommendations/application/ApplicationRecommendationsImpl.java
src/main/java/com/kruize/service/HealthService.java
src/main/java/com/kruize/service/ListApplicationsService.java
src/main/java/com/kruize/service/RecommendationsService.java
src/main/java/com/kruize/util/HttpUtil.java
tests/testAPI.sh

Add recommendations API

---

tests/testAPI.sh

Signed-off-by: Ravali Yatham <yatraval@in.ibm.com>
closes #102

Added command line arguments for API test script

---

scripts/openshift-helpers.sh

Signed-off-by: Ravali Yatham <yatraval@in.ibm.com>
closes: #104

Add openshift_terminate

---

src/main/java/com/kruize/recommendations/runtimes/java/JavaRecommendations.java
src/main/java/com/kruize/recommendations/runtimes/java/openj9/OpenJ9JavaRecommendations.java

Also implement OpenJ9JavaRecommendations.java

Add java runtimes recommendation abstraction  

---

src/main/java/com/kruize/collection/CollectMetrics.java
src/main/java/com/kruize/main/Kruize.java

Remove Prometheus references from Kruize.java

---

src/main/java/com/kruize/analysis/AnalysisImpl.java
src/main/java/com/kruize/collection/CollectMetrics.java
src/main/java/com/kruize/util/MathUtil.java

Fix recommendations reported by API being different from grafana

---

src/main/java/com/kruize/service/RecommendationsService.java
src/main/java/com/kruize/util/MathUtil.java

Fix inconsistency in memory recommendations between API and grafana

---

src/main/java/com/kruize/environment/docker/DockerEnvImpl.java
src/main/java/com/kruize/environment/kubernetes/KubernetesEnvImpl.java
src/main/java/com/kruize/recommendations/application/ApplicationRecommendationsImpl.java
src/main/java/com/kruize/service/RecommendationsService.java

Also update RecommendationsService to only show recommendations for
undeployed applications if non-zero
Closes #113 
Closes #114 

Update status of undeployed applications.

---

scripts/minikube-helpers.sh
scripts/openshift-helpers.sh

Fixes issue #141 
Signed-off-by: Chandrakala M Subramanyam <chandra-ms@in.ibm.com>

Remove the update to kruize template yaml

---

src/main/java/com/kruize/analysis/AnalysisImpl.java
src/main/java/com/kruize/analysis/runtimes/java/OpenJ9AnalysisImpl.java
src/main/java/com/kruize/metrics/runtimes/java/openj9/OpenJ9MetricCollector.java
src/main/java/com/kruize/recommendations/runtimes/java/JavaRecommendations.java
src/main/java/com/kruize/recommendations/runtimes/java/openj9/OpenJ9JavaRecommendations.java

Add analysis abstraction and implement OpenJ9AnalysisImpl

---

src/main/java/com/kruize/environment/DeploymentInfo.java
src/main/java/com/kruize/initialize/Initialize.java
src/main/java/com/kruize/util/HttpUtil.java

Add prometheus status and URL to DeploymentInfo

---

tests/test_api.sh

CLUSTER_TYPE=$1
function get_bearer_token() {
if [[ $CLUSTER_TYPE == "openshift" ]]; then
echo "Fetching AUTH_TOKEN for Openshift"
AUTH_TOKEN=$(oc whoami --show-token)
else
echo "Fetching AUTH_TOKEN for Cloudctl"
AUTH_TOKEN=$(cloudctl tokens | grep "Bearer"  | cut -d' ' -f5)
fi
}
get_bearer_token

Fetch auth token automatically if not specified in API test

---

src/main/java/com/kruize/analysis/runtimes/java/OpenJ9AnalysisImpl.java
src/main/java/com/kruize/collection/CollectMetrics.java
src/main/java/com/kruize/metrics/runtimes/java/openj9/OpenJ9MetricCollector.java

Add JavaAnalysis triplet and fix heap getting updated

---

README.md
docs/Runtimes.md

Add runtimes kruize documentation

---

src/main/java/com/kruize/service/RecommendationsService.java

Change runtime recommendations json output in RecommendationService

---

docs/README.md

Add note for dashboards not supported in some openshift setups

---

.travis.yml
Dockerfile.ppc64le
build.sh
scripts/docker-helpers.sh

This adds support for ppc64le architecture.
Fixes #142

Support for Power (ppc64le) architecture
